Import-Module VMware.PowerCLI.VCenter
Import-Module VMware.CloudServices
Import-Module VMware.Sdk.vSphere.vCenter.Identity
import-module VMware.Sdk.vSphere.vCenter.Inventory
Import-Module VMware.Sdk.vSphere.vCenter.ISO
Import-Module VMware.Sdk.vSphere.vCenter.LCM
Import-Module VMware.PowerCLI.Sdk
Import-Module VMware.Sdk.vSphere.vCenter.NamespaceManagement
Import-Module VMware.PowerCLI.Sdk.Types
Import-Module VMware.Sdk.vSphere.vCenter.Namespaces
Import-Module VMware.Sdk.vSphere.vCenter.OVF
Import-Module VMware.PowerCLI.VCenter.Types.ApplianceService
Import-Module VMware.Sdk.vSphere.vCenter.Services
Import-Module VMware.PowerCLI.VCenter.Types.CertificateManagement
Import-Module VMware.Sdk.vSphere.vCenter.Storage
Import-Module VMware.Sdk.Nsx.Policy
Import-Module VMware.Sdk.vSphere.vCenter.SystemConfig
Import-Module VMware.Sdk.Runtime
Import-Module VMware.Sdk.vSphere.vCenter.Tagging
Import-Module VMware.Sdk.vSphere
Import-Module VMware.Sdk.vSphere.vCenter.Topology
Import-Module VMware.Sdk.vSphere.Appliance
Import-Module VMware.Sdk.vSphere.vCenter.TrustedInfrastructure
Import-Module VMware.Sdk.vSphere.Appliance.Access
Import-Module VMware.Sdk.vSphere.vCenter.VCHA
Import-Module VMware.Sdk.vSphere.Appliance.Health
Import-Module VMware.Sdk.vSphere.vCenter.Vm
Import-Module VMware.Sdk.vSphere.Appliance.InfraProfile
Import-Module VMware.Sdk.vSphere.vCenter.VmTemplate
Import-Module VMware.Sdk.vSphere.Appliance.LocalAccounts
Import-Module VMware.Sdk.vSphere.vStats
Import-Module VMware.Sdk.vSphere.Appliance.Logging
Import-Module VMware.Sdk.vSphereRuntime
Import-Module VMware.Sdk.vSphere.Appliance.Networking
Import-Module VMware.Vim
Import-Module VMware.Sdk.vSphere.Appliance.Recovery
Import-Module VMware.VimAutomation.Cis.Core
Import-Module VMware.Sdk.vSphere.Appliance.SupportBundle
Import-Module VMware.VimAutomation.Cloud
Import-Module VMware.Sdk.vSphere.Appliance.System
Import-Module VMware.VimAutomation.Common
Import-Module VMware.Sdk.vSphere.Appliance.Update
Import-Module VMware.VimAutomation.Core
Import-Module VMware.Sdk.vSphere.Cis
Import-Module VMware.VimAutomation.Hcx
Import-Module VMware.Sdk.vSphere.Cis.Tagging
Import-Module VMware.VimAutomation.HorizonView
Import-Module VMware.Sdk.vSphere.Content
Import-Module VMware.VimAutomation.License
Import-Module VMware.Sdk.vSphere.ContentLibrary
Import-Module VMware.VimAutomation.Nsxt
Import-Module VMware.Sdk.vSphere.Esx.Hcl
Import-Module VMware.VimAutomation.Sdk
Import-Module VMware.Sdk.vSphere.Esx.Hosts
Import-Module VMware.VimAutomation.Security
Import-Module VMware.Sdk.vSphere.Esx.Settings
Import-Module VMware.VimAutomation.Srm
Import-Module VMware.Sdk.vSphere.VAPI.Metadata
Import-Module VMware.VimAutomation.Storage
Import-Module VMware.Sdk.vSphere.vCenter
Import-Module VMware.VimAutomation.StorageUtility
Import-Module VMware.Sdk.vSphere.vCenter.Authentication
Import-Module VMware.VimAutomation.Vds
Import-Module VMware.Sdk.vSphere.vCenter.CertManagement
Import-Module VMware.VimAutomation.Vmc
Import-Module VMware.Sdk.vSphere.vCenter.Content
Import-Module VMware.VimAutomation.vROps
Import-Module VMware.Sdk.vSphere.vCenter.Datastore
Import-Module VMware.VimAutomation.WorkloadManagement
Import-Module VMware.Sdk.vSphere.vCenter.Deployment
Import-Module VMware.VumAutomation
Import-Module VMware.Sdk.vSphere.vCenter.Guest
